#!/usr/bin/env bash
# Runs every evidence script against a live backend and saves a plain-text
# transcript to docs/demo/evidence-transcript.txt.
#
# This is the one command to run before a demo, and the file it writes is the
# artifact to show a judge who asks "prove the UI is not deciding this".
#
# Usage:  ./docs/demo/run-evidence.sh [base-url]
# Needs:  a running server (npm run dev, or npm run poc).
set -uo pipefail

BASE="${1:-http://localhost:3000}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TRANSCRIPT="$HERE/evidence-transcript.txt"
STATUS=0

# ANSI colours are great on a terminal and noise in a committed file.
strip_ansi() { sed -e 's/\x1b\[[0-9;]*m//g'; }

if ! curl -sS -o /dev/null --max-time 5 "$BASE/api/health"; then
  printf 'No server answering at %s -- start one with `npm run dev` first.\n' "$BASE" >&2
  exit 1
fi

{
  printf 'Volc Agent Launchpad -- middleware evidence transcript\n'
  printf 'Backend: %s\n' "$BASE"
  printf 'Generated by docs/demo/run-evidence.sh\n'
  printf '%s\n\n' '----------------------------------------------------------'
} > "$TRANSCRIPT"

for script in person3-evidence.sh agent-isolation-evidence.sh; do
  printf '\n### %s\n\n' "$script" | tee -a "$TRANSCRIPT"
  # Capture once, print once, save once -- so the transcript is exactly what
  # was shown on screen and cannot drift from it.
  output="$(bash "$HERE/$script" "$BASE" 2>&1)"
  script_status=$?
  printf '%s\n' "$output"
  printf '%s\n' "$output" | strip_ansi >> "$TRANSCRIPT"
  [[ $script_status -eq 0 ]] || STATUS=1
done

if [[ $STATUS -eq 0 ]]; then
  printf '\nAll evidence scripts passed. Transcript: %s\n' "$TRANSCRIPT" | tee -a "$TRANSCRIPT"
else
  printf '\nAT LEAST ONE EVIDENCE SCRIPT FAILED. Transcript: %s\n' "$TRANSCRIPT" | tee -a "$TRANSCRIPT"
fi
exit $STATUS
